### ISSUE TITLE
Not installable under Python 3

### ISSUE THREAD

**Issue by mkesper** [pycontribs/activedirectory#2]
C:\MK\src>c:\Python34\Scripts\pip.exe install activedirectory
Downloading/unpacking activedirectory
  Downloading activedirectory-0.0.8.tar.gz
  Running setup.py (path:C:\Users\kesper\AppData\Local\Temp\pip_build_kesper\act
ivedirectory\setup.py) egg_info for package activedirectory
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\kesper\AppData\Local\Temp\pip_build_kesper\activedirectory\
setup.py", line 16, in <module>
        from activedirectory.version import **version**
      File "C:\Users\kesper\AppData\Local\Temp\pip_build_kesper\activedirectory\
activedirectory__init__.py", line 16, in <module>
        from .activedirectory import ActiveDirectory
      File "C:\Users\kesper\AppData\Local\Temp\pip_build_kesper\activedirectory\
activedirectory\activedirectory.py", line 81
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\kesper\AppData\Local\Temp\pip_build_kesper\activedirectory\setu
p.py", line 16, in <module>

```
from activedirectory.version import __version__
```

  File "C:\Users\kesper\AppData\Local\Temp\pip_build_kesper\activedirectory\acti
vedirectory__init__.py", line 16, in <module>

```
from .activedirectory import ActiveDirectory
```

  File "C:\Users\kesper\AppData\Local\Temp\pip_build_kesper\activedirectory\acti
vedirectory\activedirectory.py", line 81

```
except Exception, e:

                ^
```

SyntaxError: invalid syntax

---

Cleaning up...

**Comment by mkesper** [comment]
Works with 0.13
