### ISSUE TITLE
Recursive import on installation

### ISSUE THREAD

**Issue by mkesper** [pycontribs/activedirectory#3]
``` Python
(test_activedirectory) C:\MK\src\activedirectory>python
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

(test_activedirectory) C:\MK\src\activedirectory>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from activedirectory.version import __version__
  File "C:\MK\src\activedirectory\activedirectory\__init__.py", line 16, in <mod
ule>
    from .activedirectory import ActiveDirectory
  File "C:\MK\src\activedirectory\activedirectory\activedirectory.py", line 14,
in <module>
    import ldap3
ImportError: No module named 'ldap3'
```

**Comment by ssbarnea** [comment]
In fact the problem was caused by another issue which I fixed few minutes ago. Please try again with the just released version 0.14
